// Generated by scripts/encode-specimen-loops.py. Do not edit.
//
// Each rung's `codecs` parameter was read back out of the encoded file, because a
// string that promises more than the file delivers makes the browser select that
// source and then fail, with no retry.

export interface LoopRung {
  src: string;
  codecs: string;
  width: number;
  height: number;
  bytes: number;
}

export const LOOP_LADDER: Record<string, Record<string, LoopRung[]>> = {
  "buckycatcher": {
    "dark": [
      {
        "bytes": 1277871,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/buckycatcher/loop-dark-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 742302,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/buckycatcher/loop-dark.mp4",
        "width": 1024
      }
    ],
    "light": [
      {
        "bytes": 1413558,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/buckycatcher/loop-light-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 803526,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/buckycatcher/loop-light.mp4",
        "width": 1024
      }
    ]
  },
  "capsid": {
    "dark": [
      {
        "bytes": 14870026,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/capsid/loop-dark-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 3566178,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/capsid/loop-dark.mp4",
        "width": 1024
      }
    ],
    "light": [
      {
        "bytes": 16603409,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/capsid/loop-light-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 3945766,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/capsid/loop-light.mp4",
        "width": 1024
      }
    ]
  },
  "dendrimer": {
    "dark": [
      {
        "bytes": 5089809,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/dendrimer/loop-dark-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 2239026,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/dendrimer/loop-dark.mp4",
        "width": 1024
      }
    ],
    "light": [
      {
        "bytes": 5686534,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/dendrimer/loop-light-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 2441502,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/dendrimer/loop-light.mp4",
        "width": 1024
      }
    ]
  },
  "double-gyroid": {
    "dark": [
      {
        "bytes": 4813030,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/double-gyroid/loop-dark-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 2085832,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/double-gyroid/loop-dark.mp4",
        "width": 1024
      }
    ],
    "light": [
      {
        "bytes": 4893749,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/double-gyroid/loop-light-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 2111350,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/double-gyroid/loop-light.mp4",
        "width": 1024
      }
    ]
  },
  "goldberg-cage": {
    "dark": [
      {
        "bytes": 3733837,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/goldberg-cage/loop-dark-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 2338148,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/goldberg-cage/loop-dark.mp4",
        "width": 1024
      }
    ],
    "light": [
      {
        "bytes": 4153226,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/goldberg-cage/loop-light-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 2462675,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/goldberg-cage/loop-light.mp4",
        "width": 1024
      }
    ]
  },
  "molecular-knot": {
    "dark": [
      {
        "bytes": 4235179,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/molecular-knot/loop-dark-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 2399887,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/molecular-knot/loop-dark.mp4",
        "width": 1024
      }
    ],
    "light": [
      {
        "bytes": 4306683,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/molecular-knot/loop-light-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 2433015,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/molecular-knot/loop-light.mp4",
        "width": 1024
      }
    ]
  },
  "nanotube": {
    "dark": [
      {
        "bytes": 1988330,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/nanotube/loop-dark-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 1244224,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/nanotube/loop-dark.mp4",
        "width": 1024
      }
    ],
    "light": [
      {
        "bytes": 2281769,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/nanotube/loop-light-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 1436601,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/nanotube/loop-light.mp4",
        "width": 1024
      }
    ]
  },
  "woven-cof": {
    "dark": [
      {
        "bytes": 6523933,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/woven-cof/loop-dark-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 2758745,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/woven-cof/loop-dark.mp4",
        "width": 1024
      }
    ],
    "light": [
      {
        "bytes": 6680631,
        "codecs": "av01.0.12M.10",
        "height": 2048,
        "src": "/renders/woven-cof/loop-light-2048.av1.mp4",
        "width": 2048
      },
      {
        "bytes": 2796226,
        "codecs": "avc1.640020",
        "height": 1024,
        "src": "/renders/woven-cof/loop-light.mp4",
        "width": 1024
      }
    ]
  }
};
